name: estadistica-descriptiva
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.8
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  # Added scipy for skewness calculation
  - scipy=1.13.1
  - statsmodels=0.14.2
  - scikit-learn=1.4.2
  - jupyterlab=4.1.6
  - ipykernel=6.29.3
  - ipywidgets=8.1.2
  - openpyxl=3.1.2
  - pyarrow=16.1.0
  - pip=24.0
  - pip:
      - ydata-profiling==4.6.4
